#! /usr/bin/env bash

dir="$(dirname "$(realpath "$0")")"
path="$dir/emoji_data.json"

cat "$path" | jq -r '.[] | .character + " " + .unicodeName' | dmenu -p "emojis" | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
